[package]
name = "traits"
version = "0.1.0"
edition = "2021"

[lib]
path = "stc/lib.rs"

[[bin]]
path = "src/main.rs"
name = "aggregator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
